// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login             *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password          *string                `protobuf:"bytes,2,opt,name=password"`
	xxx_hidden_MasterKeySalt     []byte                 `protobuf:"bytes,3,opt,name=master_key_salt,json=masterKeySalt"`
	xxx_hidden_MasterKeyVerifier []byte                 `protobuf:"bytes,4,opt,name=master_key_verifier,json=masterKeyVerifier"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) GetMasterKeySalt() []byte {
	if x != nil {
		return x.xxx_hidden_MasterKeySalt
	}
	return nil
}

func (x *RegisterRequest) GetMasterKeyVerifier() []byte {
	if x != nil {
		return x.xxx_hidden_MasterKeyVerifier
	}
	return nil
}

func (x *RegisterRequest) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *RegisterRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *RegisterRequest) SetMasterKeySalt(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_MasterKeySalt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *RegisterRequest) SetMasterKeyVerifier(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_MasterKeyVerifier = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *RegisterRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterRequest) HasMasterKeySalt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RegisterRequest) HasMasterKeyVerifier() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RegisterRequest) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *RegisterRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

func (x *RegisterRequest) ClearMasterKeySalt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MasterKeySalt = nil
}

func (x *RegisterRequest) ClearMasterKeyVerifier() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_MasterKeyVerifier = nil
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login             *string
	Password          *string
	MasterKeySalt     []byte
	MasterKeyVerifier []byte
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Password = b.Password
	}
	if b.MasterKeySalt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_MasterKeySalt = b.MasterKeySalt
	}
	if b.MasterKeyVerifier != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_MasterKeyVerifier = b.MasterKeyVerifier
	}
	return m0
}

type RegisterResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccessToken   *string                `protobuf:"bytes,1,opt,name=access_token,json=accessToken"`
	xxx_hidden_RefreshToken  *string                `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken"`
	xxx_hidden_MasterKeySalt []byte                 `protobuf:"bytes,3,opt,name=master_key_salt,json=masterKeySalt"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterResponse) GetAccessToken() string {
	if x != nil {
		if x.xxx_hidden_AccessToken != nil {
			return *x.xxx_hidden_AccessToken
		}
		return ""
	}
	return ""
}

func (x *RegisterResponse) GetRefreshToken() string {
	if x != nil {
		if x.xxx_hidden_RefreshToken != nil {
			return *x.xxx_hidden_RefreshToken
		}
		return ""
	}
	return ""
}

func (x *RegisterResponse) GetMasterKeySalt() []byte {
	if x != nil {
		return x.xxx_hidden_MasterKeySalt
	}
	return nil
}

func (x *RegisterResponse) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RegisterResponse) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RegisterResponse) SetMasterKeySalt(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_MasterKeySalt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *RegisterResponse) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterResponse) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterResponse) HasMasterKeySalt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RegisterResponse) ClearAccessToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AccessToken = nil
}

func (x *RegisterResponse) ClearRefreshToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RefreshToken = nil
}

func (x *RegisterResponse) ClearMasterKeySalt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MasterKeySalt = nil
}

type RegisterResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessToken   *string
	RefreshToken  *string
	MasterKeySalt []byte
}

func (b0 RegisterResponse_builder) Build() *RegisterResponse {
	m0 := &RegisterResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AccessToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_AccessToken = b.AccessToken
	}
	if b.RefreshToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_RefreshToken = b.RefreshToken
	}
	if b.MasterKeySalt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_MasterKeySalt = b.MasterKeySalt
	}
	return m0
}

type LoginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *LoginRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginRequest) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *LoginRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    *string
	Password *string
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type LoginResponse struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccessToken       *string                `protobuf:"bytes,1,opt,name=access_token,json=accessToken"`
	xxx_hidden_RefreshToken      *string                `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken"`
	xxx_hidden_MasterKeySalt     []byte                 `protobuf:"bytes,3,opt,name=master_key_salt,json=masterKeySalt"`
	xxx_hidden_MasterKeyVerifier []byte                 `protobuf:"bytes,4,opt,name=master_key_verifier,json=masterKeyVerifier"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		if x.xxx_hidden_AccessToken != nil {
			return *x.xxx_hidden_AccessToken
		}
		return ""
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		if x.xxx_hidden_RefreshToken != nil {
			return *x.xxx_hidden_RefreshToken
		}
		return ""
	}
	return ""
}

func (x *LoginResponse) GetMasterKeySalt() []byte {
	if x != nil {
		return x.xxx_hidden_MasterKeySalt
	}
	return nil
}

func (x *LoginResponse) GetMasterKeyVerifier() []byte {
	if x != nil {
		return x.xxx_hidden_MasterKeyVerifier
	}
	return nil
}

func (x *LoginResponse) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *LoginResponse) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *LoginResponse) SetMasterKeySalt(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_MasterKeySalt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *LoginResponse) SetMasterKeyVerifier(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_MasterKeyVerifier = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *LoginResponse) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginResponse) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginResponse) HasMasterKeySalt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *LoginResponse) HasMasterKeyVerifier() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *LoginResponse) ClearAccessToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AccessToken = nil
}

func (x *LoginResponse) ClearRefreshToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RefreshToken = nil
}

func (x *LoginResponse) ClearMasterKeySalt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MasterKeySalt = nil
}

func (x *LoginResponse) ClearMasterKeyVerifier() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_MasterKeyVerifier = nil
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessToken       *string
	RefreshToken      *string
	MasterKeySalt     []byte
	MasterKeyVerifier []byte
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AccessToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_AccessToken = b.AccessToken
	}
	if b.RefreshToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_RefreshToken = b.RefreshToken
	}
	if b.MasterKeySalt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_MasterKeySalt = b.MasterKeySalt
	}
	if b.MasterKeyVerifier != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_MasterKeyVerifier = b.MasterKeyVerifier
	}
	return m0
}

type RefreshRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefreshToken *string                `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_api_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		if x.xxx_hidden_RefreshToken != nil {
			return *x.xxx_hidden_RefreshToken
		}
		return ""
	}
	return ""
}

func (x *RefreshRequest) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RefreshRequest) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RefreshRequest) ClearRefreshToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RefreshToken = nil
}

type RefreshRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefreshToken *string
}

func (b0 RefreshRequest_builder) Build() *RefreshRequest {
	m0 := &RefreshRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RefreshToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_RefreshToken = b.RefreshToken
	}
	return m0
}

type RefreshResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccessToken  *string                `protobuf:"bytes,1,opt,name=access_token,json=accessToken"`
	xxx_hidden_RefreshToken *string                `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_api_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		if x.xxx_hidden_AccessToken != nil {
			return *x.xxx_hidden_AccessToken
		}
		return ""
	}
	return ""
}

func (x *RefreshResponse) GetRefreshToken() string {
	if x != nil {
		if x.xxx_hidden_RefreshToken != nil {
			return *x.xxx_hidden_RefreshToken
		}
		return ""
	}
	return ""
}

func (x *RefreshResponse) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RefreshResponse) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RefreshResponse) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RefreshResponse) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RefreshResponse) ClearAccessToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AccessToken = nil
}

func (x *RefreshResponse) ClearRefreshToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RefreshToken = nil
}

type RefreshResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessToken  *string
	RefreshToken *string
}

func (b0 RefreshResponse_builder) Build() *RefreshResponse {
	m0 := &RefreshResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AccessToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_AccessToken = b.AccessToken
	}
	if b.RefreshToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_RefreshToken = b.RefreshToken
	}
	return m0
}

type LogoutRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefreshToken *string                `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_api_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		if x.xxx_hidden_RefreshToken != nil {
			return *x.xxx_hidden_RefreshToken
		}
		return ""
	}
	return ""
}

func (x *LogoutRequest) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *LogoutRequest) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LogoutRequest) ClearRefreshToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RefreshToken = nil
}

type LogoutRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefreshToken *string
}

func (b0 LogoutRequest_builder) Build() *LogoutRequest {
	m0 := &LogoutRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RefreshToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_RefreshToken = b.RefreshToken
	}
	return m0
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_api_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LogoutResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LogoutResponse_builder) Build() *LogoutResponse {
	m0 := &LogoutResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_api_auth_proto protoreflect.FileDescriptor

const file_api_auth_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/auth.proto\x12\rgophkeeper.v1\"\x9b\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12&\n" +
	"\x0fmaster_key_salt\x18\x03 \x01(\fR\rmasterKeySalt\x12.\n" +
	"\x13master_key_verifier\x18\x04 \x01(\fR\x11masterKeyVerifier\"\x82\x01\n" +
	"\x10RegisterResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12&\n" +
	"\x0fmaster_key_salt\x18\x03 \x01(\fR\rmasterKeySalt\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xaf\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12&\n" +
	"\x0fmaster_key_salt\x18\x03 \x01(\fR\rmasterKeySalt\x12.\n" +
	"\x13master_key_verifier\x18\x04 \x01(\fR\x11masterKeyVerifier\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"Y\n" +
	"\x0fRefreshResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x10\n" +
	"\x0eLogoutResponse2\xa8\x02\n" +
	"\x04Auth\x12K\n" +
	"\bRegister\x12\x1e.gophkeeper.v1.RegisterRequest\x1a\x1f.gophkeeper.v1.RegisterResponse\x12B\n" +
	"\x05Login\x12\x1b.gophkeeper.v1.LoginRequest\x1a\x1c.gophkeeper.v1.LoginResponse\x12H\n" +
	"\aRefresh\x12\x1d.gophkeeper.v1.RefreshRequest\x1a\x1e.gophkeeper.v1.RefreshResponse\x12E\n" +
	"\x06Logout\x12\x1c.gophkeeper.v1.LogoutRequest\x1a\x1d.gophkeeper.v1.LogoutResponseB+Z)zerogravity-82/goph-keeper/internal/pb;pbb\beditionsp\xe8\a"

var file_api_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: gophkeeper.v1.RegisterRequest
	(*RegisterResponse)(nil), // 1: gophkeeper.v1.RegisterResponse
	(*LoginRequest)(nil),     // 2: gophkeeper.v1.LoginRequest
	(*LoginResponse)(nil),    // 3: gophkeeper.v1.LoginResponse
	(*RefreshRequest)(nil),   // 4: gophkeeper.v1.RefreshRequest
	(*RefreshResponse)(nil),  // 5: gophkeeper.v1.RefreshResponse
	(*LogoutRequest)(nil),    // 6: gophkeeper.v1.LogoutRequest
	(*LogoutResponse)(nil),   // 7: gophkeeper.v1.LogoutResponse
}
var file_api_auth_proto_depIdxs = []int32{
	0, // 0: gophkeeper.v1.Auth.Register:input_type -> gophkeeper.v1.RegisterRequest
	2, // 1: gophkeeper.v1.Auth.Login:input_type -> gophkeeper.v1.LoginRequest
	4, // 2: gophkeeper.v1.Auth.Refresh:input_type -> gophkeeper.v1.RefreshRequest
	6, // 3: gophkeeper.v1.Auth.Logout:input_type -> gophkeeper.v1.LogoutRequest
	1, // 4: gophkeeper.v1.Auth.Register:output_type -> gophkeeper.v1.RegisterResponse
	3, // 5: gophkeeper.v1.Auth.Login:output_type -> gophkeeper.v1.LoginResponse
	5, // 6: gophkeeper.v1.Auth.Refresh:output_type -> gophkeeper.v1.RefreshResponse
	7, // 7: gophkeeper.v1.Auth.Logout:output_type -> gophkeeper.v1.LogoutResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_proto_init() }
func file_api_auth_proto_init() {
	if File_api_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_proto_rawDesc), len(file_api_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_proto_goTypes,
		DependencyIndexes: file_api_auth_proto_depIdxs,
		MessageInfos:      file_api_auth_proto_msgTypes,
	}.Build()
	File_api_auth_proto = out.File
	file_api_auth_proto_goTypes = nil
	file_api_auth_proto_depIdxs = nil
}
