// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/records.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordType int32

const (
	RecordType_RECORD_TYPE_UNSPECIFIED RecordType = 0
	RecordType_RECORD_TYPE_CREDENTIAL  RecordType = 1
	RecordType_RECORD_TYPE_TEXT        RecordType = 2
	RecordType_RECORD_TYPE_CARD        RecordType = 3
	RecordType_RECORD_TYPE_BINARY      RecordType = 4
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0: "RECORD_TYPE_UNSPECIFIED",
		1: "RECORD_TYPE_CREDENTIAL",
		2: "RECORD_TYPE_TEXT",
		3: "RECORD_TYPE_CARD",
		4: "RECORD_TYPE_BINARY",
	}
	RecordType_value = map[string]int32{
		"RECORD_TYPE_UNSPECIFIED": 0,
		"RECORD_TYPE_CREDENTIAL":  1,
		"RECORD_TYPE_TEXT":        2,
		"RECORD_TYPE_CARD":        3,
		"RECORD_TYPE_BINARY":      4,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_records_proto_enumTypes[0].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_api_records_proto_enumTypes[0]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type UploadMode int32

const (
	UploadMode_UPLOAD_MODE_UNSPECIFIED UploadMode = 0
	UploadMode_UPLOAD_MODE_SINGLE_PART UploadMode = 1
	UploadMode_UPLOAD_MODE_MULTIPART   UploadMode = 2
)

// Enum value maps for UploadMode.
var (
	UploadMode_name = map[int32]string{
		0: "UPLOAD_MODE_UNSPECIFIED",
		1: "UPLOAD_MODE_SINGLE_PART",
		2: "UPLOAD_MODE_MULTIPART",
	}
	UploadMode_value = map[string]int32{
		"UPLOAD_MODE_UNSPECIFIED": 0,
		"UPLOAD_MODE_SINGLE_PART": 1,
		"UPLOAD_MODE_MULTIPART":   2,
	}
)

func (x UploadMode) Enum() *UploadMode {
	p := new(UploadMode)
	*p = x
	return p
}

func (x UploadMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_records_proto_enumTypes[1].Descriptor()
}

func (UploadMode) Type() protoreflect.EnumType {
	return &file_api_records_proto_enumTypes[1]
}

func (x UploadMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type UploadStatus int32

const (
	UploadStatus_UPLOAD_STATUS_UNSPECIFIED UploadStatus = 0
	UploadStatus_UPLOAD_STATUS_PENDING     UploadStatus = 1
	UploadStatus_UPLOAD_STATUS_UPLOADING   UploadStatus = 2
	UploadStatus_UPLOAD_STATUS_UPLOADED    UploadStatus = 3
	UploadStatus_UPLOAD_STATUS_FAILED      UploadStatus = 4
)

// Enum value maps for UploadStatus.
var (
	UploadStatus_name = map[int32]string{
		0: "UPLOAD_STATUS_UNSPECIFIED",
		1: "UPLOAD_STATUS_PENDING",
		2: "UPLOAD_STATUS_UPLOADING",
		3: "UPLOAD_STATUS_UPLOADED",
		4: "UPLOAD_STATUS_FAILED",
	}
	UploadStatus_value = map[string]int32{
		"UPLOAD_STATUS_UNSPECIFIED": 0,
		"UPLOAD_STATUS_PENDING":     1,
		"UPLOAD_STATUS_UPLOADING":   2,
		"UPLOAD_STATUS_UPLOADED":    3,
		"UPLOAD_STATUS_FAILED":      4,
	}
)

func (x UploadStatus) Enum() *UploadStatus {
	p := new(UploadStatus)
	*p = x
	return p
}

func (x UploadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_records_proto_enumTypes[2].Descriptor()
}

func (UploadStatus) Type() protoreflect.EnumType {
	return &file_api_records_proto_enumTypes[2]
}

func (x UploadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Record struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecordId         *string                `protobuf:"bytes,1,opt,name=record_id,json=recordId"`
	xxx_hidden_Type             RecordType             `protobuf:"varint,2,opt,name=type,enum=gophkeeper.v1.RecordType"`
	xxx_hidden_Title            *string                `protobuf:"bytes,3,opt,name=title"`
	xxx_hidden_Description      *string                `protobuf:"bytes,4,opt,name=description"`
	xxx_hidden_EncryptedDek     []byte                 `protobuf:"bytes,5,opt,name=encrypted_dek,json=encryptedDek"`
	xxx_hidden_EncryptedPayload []byte                 `protobuf:"bytes,6,opt,name=encrypted_payload,json=encryptedPayload"`
	xxx_hidden_Version          int64                  `protobuf:"varint,7,opt,name=version"`
	xxx_hidden_CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt"`
	xxx_hidden_File             *RecordFile            `protobuf:"bytes,11,opt,name=file"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_api_records_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Record) GetRecordId() string {
	if x != nil {
		if x.xxx_hidden_RecordId != nil {
			return *x.xxx_hidden_RecordId
		}
		return ""
	}
	return ""
}

func (x *Record) GetType() RecordType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *Record) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *Record) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *Record) GetEncryptedDek() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedDek
	}
	return nil
}

func (x *Record) GetEncryptedPayload() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedPayload
	}
	return nil
}

func (x *Record) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Record) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Record) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Record) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DeletedAt
	}
	return nil
}

func (x *Record) GetFile() *RecordFile {
	if x != nil {
		return x.xxx_hidden_File
	}
	return nil
}

func (x *Record) SetRecordId(v string) {
	x.xxx_hidden_RecordId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 11)
}

func (x *Record) SetType(v RecordType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 11)
}

func (x *Record) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 11)
}

func (x *Record) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 11)
}

func (x *Record) SetEncryptedDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedDek = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 11)
}

func (x *Record) SetEncryptedPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 11)
}

func (x *Record) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 11)
}

func (x *Record) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Record) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Record) SetDeletedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_DeletedAt = v
}

func (x *Record) SetFile(v *RecordFile) {
	x.xxx_hidden_File = v
}

func (x *Record) HasRecordId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Record) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Record) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Record) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Record) HasEncryptedDek() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Record) HasEncryptedPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Record) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Record) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Record) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Record) HasDeletedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DeletedAt != nil
}

func (x *Record) HasFile() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_File != nil
}

func (x *Record) ClearRecordId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RecordId = nil
}

func (x *Record) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *Record) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Title = nil
}

func (x *Record) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Description = nil
}

func (x *Record) ClearEncryptedDek() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_EncryptedDek = nil
}

func (x *Record) ClearEncryptedPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_EncryptedPayload = nil
}

func (x *Record) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Version = 0
}

func (x *Record) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Record) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

func (x *Record) ClearDeletedAt() {
	x.xxx_hidden_DeletedAt = nil
}

func (x *Record) ClearFile() {
	x.xxx_hidden_File = nil
}

type Record_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecordId         *string
	Type             *RecordType
	Title            *string
	Description      *string
	EncryptedDek     []byte
	EncryptedPayload []byte
	Version          *int64
	CreatedAt        *timestamppb.Timestamp
	UpdatedAt        *timestamppb.Timestamp
	DeletedAt        *timestamppb.Timestamp
	File             *RecordFile
}

func (b0 Record_builder) Build() *Record {
	m0 := &Record{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RecordId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 11)
		x.xxx_hidden_RecordId = b.RecordId
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 11)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 11)
		x.xxx_hidden_Title = b.Title
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 11)
		x.xxx_hidden_Description = b.Description
	}
	if b.EncryptedDek != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 11)
		x.xxx_hidden_EncryptedDek = b.EncryptedDek
	}
	if b.EncryptedPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 11)
		x.xxx_hidden_EncryptedPayload = b.EncryptedPayload
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 11)
		x.xxx_hidden_Version = *b.Version
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_DeletedAt = b.DeletedAt
	x.xxx_hidden_File = b.File
	return m0
}

type RecordFile struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UploadStatus UploadStatus           `protobuf:"varint,1,opt,name=upload_status,json=uploadStatus,enum=gophkeeper.v1.UploadStatus"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RecordFile) Reset() {
	*x = RecordFile{}
	mi := &file_api_records_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFile) ProtoMessage() {}

func (x *RecordFile) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecordFile) GetUploadStatus() UploadStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_UploadStatus
		}
	}
	return UploadStatus_UPLOAD_STATUS_UNSPECIFIED
}

func (x *RecordFile) SetUploadStatus(v UploadStatus) {
	x.xxx_hidden_UploadStatus = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RecordFile) HasUploadStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RecordFile) ClearUploadStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_UploadStatus = UploadStatus_UPLOAD_STATUS_UNSPECIFIED
}

type RecordFile_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UploadStatus *UploadStatus
}

func (b0 RecordFile_builder) Build() *RecordFile {
	m0 := &RecordFile{}
	b, x := &b0, m0
	_, _ = b, x
	if b.UploadStatus != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_UploadStatus = *b.UploadStatus
	}
	return m0
}

type RecordListItem struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecordId    *string                `protobuf:"bytes,1,opt,name=record_id,json=recordId"`
	xxx_hidden_Type        RecordType             `protobuf:"varint,2,opt,name=type,enum=gophkeeper.v1.RecordType"`
	xxx_hidden_Title       *string                `protobuf:"bytes,3,opt,name=title"`
	xxx_hidden_Description *string                `protobuf:"bytes,4,opt,name=description"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_File        *RecordFile            `protobuf:"bytes,7,opt,name=file"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RecordListItem) Reset() {
	*x = RecordListItem{}
	mi := &file_api_records_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordListItem) ProtoMessage() {}

func (x *RecordListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecordListItem) GetRecordId() string {
	if x != nil {
		if x.xxx_hidden_RecordId != nil {
			return *x.xxx_hidden_RecordId
		}
		return ""
	}
	return ""
}

func (x *RecordListItem) GetType() RecordType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *RecordListItem) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *RecordListItem) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *RecordListItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *RecordListItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *RecordListItem) GetFile() *RecordFile {
	if x != nil {
		return x.xxx_hidden_File
	}
	return nil
}

func (x *RecordListItem) SetRecordId(v string) {
	x.xxx_hidden_RecordId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *RecordListItem) SetType(v RecordType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *RecordListItem) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *RecordListItem) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *RecordListItem) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *RecordListItem) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *RecordListItem) SetFile(v *RecordFile) {
	x.xxx_hidden_File = v
}

func (x *RecordListItem) HasRecordId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RecordListItem) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RecordListItem) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RecordListItem) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RecordListItem) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *RecordListItem) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *RecordListItem) HasFile() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_File != nil
}

func (x *RecordListItem) ClearRecordId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RecordId = nil
}

func (x *RecordListItem) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *RecordListItem) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Title = nil
}

func (x *RecordListItem) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Description = nil
}

func (x *RecordListItem) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *RecordListItem) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

func (x *RecordListItem) ClearFile() {
	x.xxx_hidden_File = nil
}

type RecordListItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecordId    *string
	Type        *RecordType
	Title       *string
	Description *string
	CreatedAt   *timestamppb.Timestamp
	UpdatedAt   *timestamppb.Timestamp
	File        *RecordFile
}

func (b0 RecordListItem_builder) Build() *RecordListItem {
	m0 := &RecordListItem{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RecordId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_RecordId = b.RecordId
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Title = b.Title
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Description = b.Description
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_File = b.File
	return m0
}

type CreateRecordRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type             RecordType             `protobuf:"varint,1,opt,name=type,enum=gophkeeper.v1.RecordType"`
	xxx_hidden_Title            *string                `protobuf:"bytes,2,opt,name=title"`
	xxx_hidden_Description      *string                `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_EncryptedDek     []byte                 `protobuf:"bytes,4,opt,name=encrypted_dek,json=encryptedDek"`
	xxx_hidden_EncryptedPayload []byte                 `protobuf:"bytes,5,opt,name=encrypted_payload,json=encryptedPayload"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CreateRecordRequest) Reset() {
	*x = CreateRecordRequest{}
	mi := &file_api_records_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordRequest) ProtoMessage() {}

func (x *CreateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateRecordRequest) GetType() RecordType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *CreateRecordRequest) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *CreateRecordRequest) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *CreateRecordRequest) GetEncryptedDek() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedDek
	}
	return nil
}

func (x *CreateRecordRequest) GetEncryptedPayload() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedPayload
	}
	return nil
}

func (x *CreateRecordRequest) SetType(v RecordType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *CreateRecordRequest) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *CreateRecordRequest) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *CreateRecordRequest) SetEncryptedDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedDek = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *CreateRecordRequest) SetEncryptedPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *CreateRecordRequest) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateRecordRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateRecordRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateRecordRequest) HasEncryptedDek() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CreateRecordRequest) HasEncryptedPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CreateRecordRequest) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *CreateRecordRequest) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

func (x *CreateRecordRequest) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

func (x *CreateRecordRequest) ClearEncryptedDek() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_EncryptedDek = nil
}

func (x *CreateRecordRequest) ClearEncryptedPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_EncryptedPayload = nil
}

type CreateRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type             *RecordType
	Title            *string
	Description      *string
	EncryptedDek     []byte
	EncryptedPayload []byte
}

func (b0 CreateRecordRequest_builder) Build() *CreateRecordRequest {
	m0 := &CreateRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Title = b.Title
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Description = b.Description
	}
	if b.EncryptedDek != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_EncryptedDek = b.EncryptedDek
	}
	if b.EncryptedPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_EncryptedPayload = b.EncryptedPayload
	}
	return m0
}

type CreateRecordResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecordId    *string                `protobuf:"bytes,1,opt,name=record_id,json=recordId"`
	xxx_hidden_Version     int64                  `protobuf:"varint,2,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateRecordResponse) Reset() {
	*x = CreateRecordResponse{}
	mi := &file_api_records_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordResponse) ProtoMessage() {}

func (x *CreateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateRecordResponse) GetRecordId() string {
	if x != nil {
		if x.xxx_hidden_RecordId != nil {
			return *x.xxx_hidden_RecordId
		}
		return ""
	}
	return ""
}

func (x *CreateRecordResponse) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *CreateRecordResponse) SetRecordId(v string) {
	x.xxx_hidden_RecordId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateRecordResponse) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CreateRecordResponse) HasRecordId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateRecordResponse) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateRecordResponse) ClearRecordId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RecordId = nil
}

func (x *CreateRecordResponse) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = 0
}

type CreateRecordResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecordId *string
	Version  *int64
}

func (b0 CreateRecordResponse_builder) Build() *CreateRecordResponse {
	m0 := &CreateRecordResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RecordId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_RecordId = b.RecordId
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_api_records_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListRecordsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListRecordsRequest_builder) Build() *ListRecordsRequest {
	m0 := &ListRecordsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListRecordsResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*RecordListItem     `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_api_records_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRecordsResponse) GetItems() []*RecordListItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *ListRecordsResponse) SetItems(v []*RecordListItem) {
	x.xxx_hidden_Items = &v
}

type ListRecordsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*RecordListItem
}

func (b0 ListRecordsResponse_builder) Build() *ListRecordsResponse {
	m0 := &ListRecordsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

type GetRecordRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecordId    *string                `protobuf:"bytes,1,opt,name=record_id,json=recordId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_api_records_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRecordRequest) GetRecordId() string {
	if x != nil {
		if x.xxx_hidden_RecordId != nil {
			return *x.xxx_hidden_RecordId
		}
		return ""
	}
	return ""
}

func (x *GetRecordRequest) SetRecordId(v string) {
	x.xxx_hidden_RecordId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetRecordRequest) HasRecordId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetRecordRequest) ClearRecordId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RecordId = nil
}

type GetRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecordId *string
}

func (b0 GetRecordRequest_builder) Build() *GetRecordRequest {
	m0 := &GetRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RecordId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_RecordId = b.RecordId
	}
	return m0
}

type GetRecordResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Record *Record                `protobuf:"bytes,1,opt,name=record"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetRecordResponse) Reset() {
	*x = GetRecordResponse{}
	mi := &file_api_records_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResponse) ProtoMessage() {}

func (x *GetRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRecordResponse) GetRecord() *Record {
	if x != nil {
		return x.xxx_hidden_Record
	}
	return nil
}

func (x *GetRecordResponse) SetRecord(v *Record) {
	x.xxx_hidden_Record = v
}

func (x *GetRecordResponse) HasRecord() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Record != nil
}

func (x *GetRecordResponse) ClearRecord() {
	x.xxx_hidden_Record = nil
}

type GetRecordResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Record *Record
}

func (b0 GetRecordResponse_builder) Build() *GetRecordResponse {
	m0 := &GetRecordResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Record = b.Record
	return m0
}

type UpdateRecordRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecordId         *string                `protobuf:"bytes,1,opt,name=record_id,json=recordId"`
	xxx_hidden_Title            *string                `protobuf:"bytes,2,opt,name=title"`
	xxx_hidden_Description      *string                `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_EncryptedDek     []byte                 `protobuf:"bytes,4,opt,name=encrypted_dek,json=encryptedDek"`
	xxx_hidden_EncryptedPayload []byte                 `protobuf:"bytes,5,opt,name=encrypted_payload,json=encryptedPayload"`
	xxx_hidden_ExpectedVersion  int64                  `protobuf:"varint,6,opt,name=expected_version,json=expectedVersion"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	mi := &file_api_records_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateRecordRequest) GetRecordId() string {
	if x != nil {
		if x.xxx_hidden_RecordId != nil {
			return *x.xxx_hidden_RecordId
		}
		return ""
	}
	return ""
}

func (x *UpdateRecordRequest) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *UpdateRecordRequest) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *UpdateRecordRequest) GetEncryptedDek() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedDek
	}
	return nil
}

func (x *UpdateRecordRequest) GetEncryptedPayload() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedPayload
	}
	return nil
}

func (x *UpdateRecordRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.xxx_hidden_ExpectedVersion
	}
	return 0
}

func (x *UpdateRecordRequest) SetRecordId(v string) {
	x.xxx_hidden_RecordId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *UpdateRecordRequest) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *UpdateRecordRequest) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *UpdateRecordRequest) SetEncryptedDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedDek = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *UpdateRecordRequest) SetEncryptedPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *UpdateRecordRequest) SetExpectedVersion(v int64) {
	x.xxx_hidden_ExpectedVersion = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *UpdateRecordRequest) HasRecordId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateRecordRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateRecordRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdateRecordRequest) HasEncryptedDek() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UpdateRecordRequest) HasEncryptedPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UpdateRecordRequest) HasExpectedVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *UpdateRecordRequest) ClearRecordId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RecordId = nil
}

func (x *UpdateRecordRequest) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

func (x *UpdateRecordRequest) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

func (x *UpdateRecordRequest) ClearEncryptedDek() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_EncryptedDek = nil
}

func (x *UpdateRecordRequest) ClearEncryptedPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_EncryptedPayload = nil
}

func (x *UpdateRecordRequest) ClearExpectedVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ExpectedVersion = 0
}

type UpdateRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecordId         *string
	Title            *string
	Description      *string
	EncryptedDek     []byte
	EncryptedPayload []byte
	ExpectedVersion  *int64
}

func (b0 UpdateRecordRequest_builder) Build() *UpdateRecordRequest {
	m0 := &UpdateRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RecordId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_RecordId = b.RecordId
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Title = b.Title
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Description = b.Description
	}
	if b.EncryptedDek != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_EncryptedDek = b.EncryptedDek
	}
	if b.EncryptedPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_EncryptedPayload = b.EncryptedPayload
	}
	if b.ExpectedVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_ExpectedVersion = *b.ExpectedVersion
	}
	return m0
}

type UpdateRecordResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecordId    *string                `protobuf:"bytes,1,opt,name=record_id,json=recordId"`
	xxx_hidden_Version     int64                  `protobuf:"varint,2,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateRecordResponse) Reset() {
	*x = UpdateRecordResponse{}
	mi := &file_api_records_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordResponse) ProtoMessage() {}

func (x *UpdateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateRecordResponse) GetRecordId() string {
	if x != nil {
		if x.xxx_hidden_RecordId != nil {
			return *x.xxx_hidden_RecordId
		}
		return ""
	}
	return ""
}

func (x *UpdateRecordResponse) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *UpdateRecordResponse) SetRecordId(v string) {
	x.xxx_hidden_RecordId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UpdateRecordResponse) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *UpdateRecordResponse) HasRecordId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateRecordResponse) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateRecordResponse) ClearRecordId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RecordId = nil
}

func (x *UpdateRecordResponse) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = 0
}

type UpdateRecordResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecordId *string
	Version  *int64
}

func (b0 UpdateRecordResponse_builder) Build() *UpdateRecordResponse {
	m0 := &UpdateRecordResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RecordId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_RecordId = b.RecordId
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type DeleteRecordRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecordId    *string                `protobuf:"bytes,1,opt,name=record_id,json=recordId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_api_records_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRecordRequest) GetRecordId() string {
	if x != nil {
		if x.xxx_hidden_RecordId != nil {
			return *x.xxx_hidden_RecordId
		}
		return ""
	}
	return ""
}

func (x *DeleteRecordRequest) SetRecordId(v string) {
	x.xxx_hidden_RecordId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteRecordRequest) HasRecordId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteRecordRequest) ClearRecordId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RecordId = nil
}

type DeleteRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecordId *string
}

func (b0 DeleteRecordRequest_builder) Build() *DeleteRecordRequest {
	m0 := &DeleteRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RecordId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_RecordId = b.RecordId
	}
	return m0
}

type DeleteRecordResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecordId    *string                `protobuf:"bytes,1,opt,name=record_id,json=recordId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteRecordResponse) Reset() {
	*x = DeleteRecordResponse{}
	mi := &file_api_records_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordResponse) ProtoMessage() {}

func (x *DeleteRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRecordResponse) GetRecordId() string {
	if x != nil {
		if x.xxx_hidden_RecordId != nil {
			return *x.xxx_hidden_RecordId
		}
		return ""
	}
	return ""
}

func (x *DeleteRecordResponse) SetRecordId(v string) {
	x.xxx_hidden_RecordId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteRecordResponse) HasRecordId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteRecordResponse) ClearRecordId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RecordId = nil
}

type DeleteRecordResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecordId *string
}

func (b0 DeleteRecordResponse_builder) Build() *DeleteRecordResponse {
	m0 := &DeleteRecordResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RecordId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_RecordId = b.RecordId
	}
	return m0
}

type UploadFileRequest struct {
	state              protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Payload isUploadFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_api_records_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadFileRequest) GetMetadata() *UploadFileMetadata {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*uploadFileRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadFileRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*uploadFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *UploadFileRequest) SetMetadata(v *UploadFileMetadata) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &uploadFileRequest_Metadata{v}
}

func (x *UploadFileRequest) SetChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Payload = &uploadFileRequest_Chunk{v}
}

func (x *UploadFileRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *UploadFileRequest) HasMetadata() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*uploadFileRequest_Metadata)
	return ok
}

func (x *UploadFileRequest) HasChunk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*uploadFileRequest_Chunk)
	return ok
}

func (x *UploadFileRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *UploadFileRequest) ClearMetadata() {
	if _, ok := x.xxx_hidden_Payload.(*uploadFileRequest_Metadata); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *UploadFileRequest) ClearChunk() {
	if _, ok := x.xxx_hidden_Payload.(*uploadFileRequest_Chunk); ok {
		x.xxx_hidden_Payload = nil
	}
}

const UploadFileRequest_Payload_not_set_case case_UploadFileRequest_Payload = 0
const UploadFileRequest_Metadata_case case_UploadFileRequest_Payload = 1
const UploadFileRequest_Chunk_case case_UploadFileRequest_Payload = 2

func (x *UploadFileRequest) WhichPayload() case_UploadFileRequest_Payload {
	if x == nil {
		return UploadFileRequest_Payload_not_set_case
	}
	switch x.xxx_hidden_Payload.(type) {
	case *uploadFileRequest_Metadata:
		return UploadFileRequest_Metadata_case
	case *uploadFileRequest_Chunk:
		return UploadFileRequest_Chunk_case
	default:
		return UploadFileRequest_Payload_not_set_case
	}
}

type UploadFileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Payload:
	Metadata *UploadFileMetadata
	Chunk    []byte
	// -- end of xxx_hidden_Payload
}

func (b0 UploadFileRequest_builder) Build() *UploadFileRequest {
	m0 := &UploadFileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Metadata != nil {
		x.xxx_hidden_Payload = &uploadFileRequest_Metadata{b.Metadata}
	}
	if b.Chunk != nil {
		x.xxx_hidden_Payload = &uploadFileRequest_Chunk{b.Chunk}
	}
	return m0
}

type case_UploadFileRequest_Payload protoreflect.FieldNumber

func (x case_UploadFileRequest_Payload) String() string {
	md := file_api_records_proto_msgTypes[13].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUploadFileRequest_Payload interface {
	isUploadFileRequest_Payload()
}

type uploadFileRequest_Metadata struct {
	Metadata *UploadFileMetadata `protobuf:"bytes,1,opt,name=metadata,oneof"`
}

type uploadFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,oneof"`
}

func (*uploadFileRequest_Metadata) isUploadFileRequest_Payload() {}

func (*uploadFileRequest_Chunk) isUploadFileRequest_Payload() {}

type UploadFileMetadata struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecordId      *string                `protobuf:"bytes,1,opt,name=record_id,json=recordId"`
	xxx_hidden_EncryptedSize int64                  `protobuf:"varint,2,opt,name=encrypted_size,json=encryptedSize"`
	xxx_hidden_UploadMode    UploadMode             `protobuf:"varint,3,opt,name=upload_mode,json=uploadMode,enum=gophkeeper.v1.UploadMode"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UploadFileMetadata) Reset() {
	*x = UploadFileMetadata{}
	mi := &file_api_records_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileMetadata) ProtoMessage() {}

func (x *UploadFileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadFileMetadata) GetRecordId() string {
	if x != nil {
		if x.xxx_hidden_RecordId != nil {
			return *x.xxx_hidden_RecordId
		}
		return ""
	}
	return ""
}

func (x *UploadFileMetadata) GetEncryptedSize() int64 {
	if x != nil {
		return x.xxx_hidden_EncryptedSize
	}
	return 0
}

func (x *UploadFileMetadata) GetUploadMode() UploadMode {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_UploadMode
		}
	}
	return UploadMode_UPLOAD_MODE_UNSPECIFIED
}

func (x *UploadFileMetadata) SetRecordId(v string) {
	x.xxx_hidden_RecordId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *UploadFileMetadata) SetEncryptedSize(v int64) {
	x.xxx_hidden_EncryptedSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *UploadFileMetadata) SetUploadMode(v UploadMode) {
	x.xxx_hidden_UploadMode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *UploadFileMetadata) HasRecordId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UploadFileMetadata) HasEncryptedSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UploadFileMetadata) HasUploadMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UploadFileMetadata) ClearRecordId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RecordId = nil
}

func (x *UploadFileMetadata) ClearEncryptedSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EncryptedSize = 0
}

func (x *UploadFileMetadata) ClearUploadMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_UploadMode = UploadMode_UPLOAD_MODE_UNSPECIFIED
}

type UploadFileMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecordId      *string
	EncryptedSize *int64
	UploadMode    *UploadMode
}

func (b0 UploadFileMetadata_builder) Build() *UploadFileMetadata {
	m0 := &UploadFileMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RecordId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_RecordId = b.RecordId
	}
	if b.EncryptedSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_EncryptedSize = *b.EncryptedSize
	}
	if b.UploadMode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_UploadMode = *b.UploadMode
	}
	return m0
}

type UploadFileResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecordId     *string                `protobuf:"bytes,1,opt,name=record_id,json=recordId"`
	xxx_hidden_UploadStatus UploadStatus           `protobuf:"varint,2,opt,name=upload_status,json=uploadStatus,enum=gophkeeper.v1.UploadStatus"`
	xxx_hidden_Version      int64                  `protobuf:"varint,3,opt,name=version"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_api_records_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadFileResponse) GetRecordId() string {
	if x != nil {
		if x.xxx_hidden_RecordId != nil {
			return *x.xxx_hidden_RecordId
		}
		return ""
	}
	return ""
}

func (x *UploadFileResponse) GetUploadStatus() UploadStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_UploadStatus
		}
	}
	return UploadStatus_UPLOAD_STATUS_UNSPECIFIED
}

func (x *UploadFileResponse) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *UploadFileResponse) SetRecordId(v string) {
	x.xxx_hidden_RecordId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *UploadFileResponse) SetUploadStatus(v UploadStatus) {
	x.xxx_hidden_UploadStatus = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *UploadFileResponse) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *UploadFileResponse) HasRecordId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UploadFileResponse) HasUploadStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UploadFileResponse) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UploadFileResponse) ClearRecordId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RecordId = nil
}

func (x *UploadFileResponse) ClearUploadStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_UploadStatus = UploadStatus_UPLOAD_STATUS_UNSPECIFIED
}

func (x *UploadFileResponse) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Version = 0
}

type UploadFileResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecordId     *string
	UploadStatus *UploadStatus
	Version      *int64
}

func (b0 UploadFileResponse_builder) Build() *UploadFileResponse {
	m0 := &UploadFileResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RecordId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_RecordId = b.RecordId
	}
	if b.UploadStatus != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_UploadStatus = *b.UploadStatus
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type DownloadFileRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecordId    *string                `protobuf:"bytes,1,opt,name=record_id,json=recordId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_api_records_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadFileRequest) GetRecordId() string {
	if x != nil {
		if x.xxx_hidden_RecordId != nil {
			return *x.xxx_hidden_RecordId
		}
		return ""
	}
	return ""
}

func (x *DownloadFileRequest) SetRecordId(v string) {
	x.xxx_hidden_RecordId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DownloadFileRequest) HasRecordId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DownloadFileRequest) ClearRecordId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RecordId = nil
}

type DownloadFileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecordId *string
}

func (b0 DownloadFileRequest_builder) Build() *DownloadFileRequest {
	m0 := &DownloadFileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RecordId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_RecordId = b.RecordId
	}
	return m0
}

type DownloadFileResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Chunk       []byte                 `protobuf:"bytes,1,opt,name=chunk"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_api_records_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_records_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadFileResponse) GetChunk() []byte {
	if x != nil {
		return x.xxx_hidden_Chunk
	}
	return nil
}

func (x *DownloadFileResponse) SetChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Chunk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DownloadFileResponse) HasChunk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DownloadFileResponse) ClearChunk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Chunk = nil
}

type DownloadFileResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Chunk []byte
}

func (b0 DownloadFileResponse_builder) Build() *DownloadFileResponse {
	m0 := &DownloadFileResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Chunk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Chunk = b.Chunk
	}
	return m0
}

var File_api_records_proto protoreflect.FileDescriptor

const file_api_records_proto_rawDesc = "" +
	"\n" +
	"\x11api/records.proto\x12\rgophkeeper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x03\n" +
	"\x06Record\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.RecordTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rencrypted_dek\x18\x05 \x01(\fR\fencryptedDek\x12+\n" +
	"\x11encrypted_payload\x18\x06 \x01(\fR\x10encryptedPayload\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12-\n" +
	"\x04file\x18\v \x01(\v2\x19.gophkeeper.v1.RecordFileR\x04file\"N\n" +
	"\n" +
	"RecordFile\x12@\n" +
	"\rupload_status\x18\x01 \x01(\x0e2\x1b.gophkeeper.v1.UploadStatusR\fuploadStatus\"\xb9\x02\n" +
	"\x0eRecordListItem\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.RecordTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12-\n" +
	"\x04file\x18\a \x01(\v2\x19.gophkeeper.v1.RecordFileR\x04file\"\xce\x01\n" +
	"\x13CreateRecordRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.gophkeeper.v1.RecordTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rencrypted_dek\x18\x04 \x01(\fR\fencryptedDek\x12+\n" +
	"\x11encrypted_payload\x18\x05 \x01(\fR\x10encryptedPayload\"M\n" +
	"\x14CreateRecordResponse\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"\x14\n" +
	"\x12ListRecordsRequest\"J\n" +
	"\x13ListRecordsResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.gophkeeper.v1.RecordListItemR\x05items\"/\n" +
	"\x10GetRecordRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\"B\n" +
	"\x11GetRecordResponse\x12-\n" +
	"\x06record\x18\x01 \x01(\v2\x15.gophkeeper.v1.RecordR\x06record\"\xe7\x01\n" +
	"\x13UpdateRecordRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rencrypted_dek\x18\x04 \x01(\fR\fencryptedDek\x12+\n" +
	"\x11encrypted_payload\x18\x05 \x01(\fR\x10encryptedPayload\x12)\n" +
	"\x10expected_version\x18\x06 \x01(\x03R\x0fexpectedVersion\"M\n" +
	"\x14UpdateRecordResponse\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"2\n" +
	"\x13DeleteRecordRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\"3\n" +
	"\x14DeleteRecordResponse\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\"w\n" +
	"\x11UploadFileRequest\x12?\n" +
	"\bmetadata\x18\x01 \x01(\v2!.gophkeeper.v1.UploadFileMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"\x94\x01\n" +
	"\x12UploadFileMetadata\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12%\n" +
	"\x0eencrypted_size\x18\x02 \x01(\x03R\rencryptedSize\x12:\n" +
	"\vupload_mode\x18\x03 \x01(\x0e2\x19.gophkeeper.v1.UploadModeR\n" +
	"uploadMode\"\x8d\x01\n" +
	"\x12UploadFileResponse\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12@\n" +
	"\rupload_status\x18\x02 \x01(\x0e2\x1b.gophkeeper.v1.UploadStatusR\fuploadStatus\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"2\n" +
	"\x13DownloadFileRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\",\n" +
	"\x14DownloadFileResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk*\x89\x01\n" +
	"\n" +
	"RecordType\x12\x1b\n" +
	"\x17RECORD_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RECORD_TYPE_CREDENTIAL\x10\x01\x12\x14\n" +
	"\x10RECORD_TYPE_TEXT\x10\x02\x12\x14\n" +
	"\x10RECORD_TYPE_CARD\x10\x03\x12\x16\n" +
	"\x12RECORD_TYPE_BINARY\x10\x04*a\n" +
	"\n" +
	"UploadMode\x12\x1b\n" +
	"\x17UPLOAD_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17UPLOAD_MODE_SINGLE_PART\x10\x01\x12\x19\n" +
	"\x15UPLOAD_MODE_MULTIPART\x10\x02*\x9b\x01\n" +
	"\fUploadStatus\x12\x1d\n" +
	"\x19UPLOAD_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15UPLOAD_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17UPLOAD_STATUS_UPLOADING\x10\x02\x12\x1a\n" +
	"\x16UPLOAD_STATUS_UPLOADED\x10\x03\x12\x18\n" +
	"\x14UPLOAD_STATUS_FAILED\x10\x042\xea\x04\n" +
	"\aRecords\x12W\n" +
	"\fCreateRecord\x12\".gophkeeper.v1.CreateRecordRequest\x1a#.gophkeeper.v1.CreateRecordResponse\x12T\n" +
	"\vListRecords\x12!.gophkeeper.v1.ListRecordsRequest\x1a\".gophkeeper.v1.ListRecordsResponse\x12N\n" +
	"\tGetRecord\x12\x1f.gophkeeper.v1.GetRecordRequest\x1a .gophkeeper.v1.GetRecordResponse\x12W\n" +
	"\fUpdateRecord\x12\".gophkeeper.v1.UpdateRecordRequest\x1a#.gophkeeper.v1.UpdateRecordResponse\x12W\n" +
	"\fDeleteRecord\x12\".gophkeeper.v1.DeleteRecordRequest\x1a#.gophkeeper.v1.DeleteRecordResponse\x12S\n" +
	"\n" +
	"UploadFile\x12 .gophkeeper.v1.UploadFileRequest\x1a!.gophkeeper.v1.UploadFileResponse(\x01\x12Y\n" +
	"\fDownloadFile\x12\".gophkeeper.v1.DownloadFileRequest\x1a#.gophkeeper.v1.DownloadFileResponse0\x01B+Z)zerogravity-82/goph-keeper/internal/pb;pbb\beditionsp\xe8\a"

var file_api_records_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_records_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_records_proto_goTypes = []any{
	(RecordType)(0),               // 0: gophkeeper.v1.RecordType
	(UploadMode)(0),               // 1: gophkeeper.v1.UploadMode
	(UploadStatus)(0),             // 2: gophkeeper.v1.UploadStatus
	(*Record)(nil),                // 3: gophkeeper.v1.Record
	(*RecordFile)(nil),            // 4: gophkeeper.v1.RecordFile
	(*RecordListItem)(nil),        // 5: gophkeeper.v1.RecordListItem
	(*CreateRecordRequest)(nil),   // 6: gophkeeper.v1.CreateRecordRequest
	(*CreateRecordResponse)(nil),  // 7: gophkeeper.v1.CreateRecordResponse
	(*ListRecordsRequest)(nil),    // 8: gophkeeper.v1.ListRecordsRequest
	(*ListRecordsResponse)(nil),   // 9: gophkeeper.v1.ListRecordsResponse
	(*GetRecordRequest)(nil),      // 10: gophkeeper.v1.GetRecordRequest
	(*GetRecordResponse)(nil),     // 11: gophkeeper.v1.GetRecordResponse
	(*UpdateRecordRequest)(nil),   // 12: gophkeeper.v1.UpdateRecordRequest
	(*UpdateRecordResponse)(nil),  // 13: gophkeeper.v1.UpdateRecordResponse
	(*DeleteRecordRequest)(nil),   // 14: gophkeeper.v1.DeleteRecordRequest
	(*DeleteRecordResponse)(nil),  // 15: gophkeeper.v1.DeleteRecordResponse
	(*UploadFileRequest)(nil),     // 16: gophkeeper.v1.UploadFileRequest
	(*UploadFileMetadata)(nil),    // 17: gophkeeper.v1.UploadFileMetadata
	(*UploadFileResponse)(nil),    // 18: gophkeeper.v1.UploadFileResponse
	(*DownloadFileRequest)(nil),   // 19: gophkeeper.v1.DownloadFileRequest
	(*DownloadFileResponse)(nil),  // 20: gophkeeper.v1.DownloadFileResponse
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_api_records_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.v1.Record.type:type_name -> gophkeeper.v1.RecordType
	21, // 1: gophkeeper.v1.Record.created_at:type_name -> google.protobuf.Timestamp
	21, // 2: gophkeeper.v1.Record.updated_at:type_name -> google.protobuf.Timestamp
	21, // 3: gophkeeper.v1.Record.deleted_at:type_name -> google.protobuf.Timestamp
	4,  // 4: gophkeeper.v1.Record.file:type_name -> gophkeeper.v1.RecordFile
	2,  // 5: gophkeeper.v1.RecordFile.upload_status:type_name -> gophkeeper.v1.UploadStatus
	0,  // 6: gophkeeper.v1.RecordListItem.type:type_name -> gophkeeper.v1.RecordType
	21, // 7: gophkeeper.v1.RecordListItem.created_at:type_name -> google.protobuf.Timestamp
	21, // 8: gophkeeper.v1.RecordListItem.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 9: gophkeeper.v1.RecordListItem.file:type_name -> gophkeeper.v1.RecordFile
	0,  // 10: gophkeeper.v1.CreateRecordRequest.type:type_name -> gophkeeper.v1.RecordType
	5,  // 11: gophkeeper.v1.ListRecordsResponse.items:type_name -> gophkeeper.v1.RecordListItem
	3,  // 12: gophkeeper.v1.GetRecordResponse.record:type_name -> gophkeeper.v1.Record
	17, // 13: gophkeeper.v1.UploadFileRequest.metadata:type_name -> gophkeeper.v1.UploadFileMetadata
	1,  // 14: gophkeeper.v1.UploadFileMetadata.upload_mode:type_name -> gophkeeper.v1.UploadMode
	2,  // 15: gophkeeper.v1.UploadFileResponse.upload_status:type_name -> gophkeeper.v1.UploadStatus
	6,  // 16: gophkeeper.v1.Records.CreateRecord:input_type -> gophkeeper.v1.CreateRecordRequest
	8,  // 17: gophkeeper.v1.Records.ListRecords:input_type -> gophkeeper.v1.ListRecordsRequest
	10, // 18: gophkeeper.v1.Records.GetRecord:input_type -> gophkeeper.v1.GetRecordRequest
	12, // 19: gophkeeper.v1.Records.UpdateRecord:input_type -> gophkeeper.v1.UpdateRecordRequest
	14, // 20: gophkeeper.v1.Records.DeleteRecord:input_type -> gophkeeper.v1.DeleteRecordRequest
	16, // 21: gophkeeper.v1.Records.UploadFile:input_type -> gophkeeper.v1.UploadFileRequest
	19, // 22: gophkeeper.v1.Records.DownloadFile:input_type -> gophkeeper.v1.DownloadFileRequest
	7,  // 23: gophkeeper.v1.Records.CreateRecord:output_type -> gophkeeper.v1.CreateRecordResponse
	9,  // 24: gophkeeper.v1.Records.ListRecords:output_type -> gophkeeper.v1.ListRecordsResponse
	11, // 25: gophkeeper.v1.Records.GetRecord:output_type -> gophkeeper.v1.GetRecordResponse
	13, // 26: gophkeeper.v1.Records.UpdateRecord:output_type -> gophkeeper.v1.UpdateRecordResponse
	15, // 27: gophkeeper.v1.Records.DeleteRecord:output_type -> gophkeeper.v1.DeleteRecordResponse
	18, // 28: gophkeeper.v1.Records.UploadFile:output_type -> gophkeeper.v1.UploadFileResponse
	20, // 29: gophkeeper.v1.Records.DownloadFile:output_type -> gophkeeper.v1.DownloadFileResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_records_proto_init() }
func file_api_records_proto_init() {
	if File_api_records_proto != nil {
		return
	}
	file_api_records_proto_msgTypes[13].OneofWrappers = []any{
		(*uploadFileRequest_Metadata)(nil),
		(*uploadFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_records_proto_rawDesc), len(file_api_records_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_records_proto_goTypes,
		DependencyIndexes: file_api_records_proto_depIdxs,
		EnumInfos:         file_api_records_proto_enumTypes,
		MessageInfos:      file_api_records_proto_msgTypes,
	}.Build()
	File_api_records_proto = out.File
	file_api_records_proto_goTypes = nil
	file_api_records_proto_depIdxs = nil
}
