grpc_address: localhost:3202
database_uri: postgres://gophkeeper:userpassword@localhost:5432/gophkeeper?sslmode=disable
access_token_ttl: 15m
refresh_token_ttl: 720h
file_storage:
  endpoint: localhost:9000
  bucket: gophkeeper
  use_ssl: false
logging:
  format: text
  level: debug
  add_source: true
